### PR TITLE
Added file encryption (fixed)

### PR DESCRIPTION
**Pull request by acerbisgianluca**
I added support for file encryption using [Cryptr](https://www.npmjs.com/package/cryptr).
If an encryption key isn't provided it still uses plain text.

I have already tested it and **it works**! I haven't changed version number.

Edit: fixed formatter issue and created feature branch.

### CODE REVIEW

**Comment by ivanmarban** [comment]
I'm getting this error while cookie file already exists:

```javascript
/workspace/tough-cookie-file-store/lib/file-store.js:259
                dataJson[domainName][pathName][cookieName] = tough.fromJSON(JSON.stringify(dataJson[domainName][pathName][cookieName]));
                                                           ^

TypeError: Cannot assign to read only property '0' of string '"'
    at loadFromFile (/workspace/tough-cookie-file-store/lib/file-store.js:259:60)
    at new FileCookieStore (/workspace/tough-cookie-file-store/lib/file-store.js:19:5)
    at Object.<anonymous> (/workspace/tough-cookie-file-store/test.js:6:21)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11
```
Quick test script:

```javascript
var cookieStore = require('./index.js');
var request = require('request');

var j = request.jar(new cookieStore('./cookie.json'));
request = request.defaults({ jar : j })
request('http://www.google.com', function() {
  request('http://images.google.com')
})
```
This behavior did not occur with the previous code. With encryption key parameter, seems to work fine.

Another issue, if you have already started using the library with an unencrypted cookie, and you want to start using encryption, you are forced to delete the cookie before you start using the encryption. The same happens in reverse. Maybe this is not a desired behaviour...

**Comment by acerbisgianluca** [comment]
I almost fixed all of those problems, but if the user wants to stop using encryption, how can I rollback if he doesn't pass the encryption key as an argument? Encrypt a file is theoretically an irreversible action without a key

**Comment by ivanmarban** [comment]
With your actual approach, if the cookie file do not exists an error is thrown...

I think it could be better moving the logic to `loadFromFile` function:

```javascript

'use strict';
var tough = require('tough-cookie');
var Store = tough.Store;
var permuteDomain = tough.permuteDomain;
var permutePath = tough.permutePath;
var util = require('util');
var fs = require('fs');
var Cryptr = require('cryptr');

function FileCookieStore(filePath, encryptionKey) {
    Store.call(this);
    this.idx = {}; // idx is memory cache
    this.filePath = filePath;
    this.cryptr = null;
    var self = this;
    if (encryptionKey) {
        this.cryptr = new Cryptr(encryptionKey);
    }
    loadFromFile(this.filePath, this.cryptr, function(dataJson) {
        if (dataJson) {
            self.idx = dataJson;
        }
    })
}

...

// Avoid parallel writes to the same file
var _writing_ = {};
function writeFile(filePath, cryptr, data, done) {
    var dataJson = cryptr === null ? JSON.stringify(data) : cryptr.encrypt(JSON.stringify(data));
    var wo = { done: done, next: [] };
    _writing_[filePath] = wo;
    fs.writeFile(filePath, dataJson, function (err) {
        // If we have new pending writes, execute them now
        if ( wo.next.length ) {
            writeFile(filePath, cryptr, wo.data, wo.next);
        }
        else {
            delete _writing_[filePath];
        }
        if (err) throw err;
        wo.done.forEach(function(cb) {
            cb();
        });
    });
}

function saveToFile(filePath, cryptr, data, cb) {
    var wo = _writing_[filePath];
    // If not writing to this file, start writing right now
    if ( !wo ) {
        writeFile(filePath, cryptr, data, [cb]);
    }
    // If writing in process, add to pending
    else {
        wo.data = data;
        wo.next.push(cb);
    }
}

function loadFromFile(filePath, cryptr, cb) {
    if (fs.existsSync(filePath)) {
        var data = fs.readFileSync(filePath, 'utf8');
    } else {
        var data = null;
    }

    if (data) {
        try {
            // check encryption here, throw error... ?
            var dataJson = cryptr === null ? JSON.parse(data) : JSON.parse(cryptr.decrypt(data));
        } catch (e) {
            throw new Error('Could not parse cookie file ' + filePath + '. Please ensure it is not corrupted.');
        }
    } else {
        var dataJson = null;
    }

    for (var domainName in dataJson) {
        for (var pathName in dataJson[domainName]) {
            for (var cookieName in dataJson[domainName][pathName]) {
                dataJson[domainName][pathName][cookieName] = tough.fromJSON(JSON.stringify(dataJson[domainName][pathName][cookieName]));
            }
        }
    }
    cb(dataJson);
}
...

```
By the way, you are right about having a previous cookie encrypted and not providing a encryption key... didn't realized about it.

Maybe could be a good idea having encryption behaviour as much simple as possible. If you want to use encrytion use it from the begining, if not let's throw an error. What do you think ?

**Comment by acerbisgianluca** [comment]
Oh yes, I didn't check if the file exists.
Btw I like your idea, I'm commiting it this afternoon

**Comment by ivanmarban** [comment]
Closed as this PR is not longer valid for the new version

**Pull request closed without merging**
